[theme]
# Original primaryColor = "#1f77b4"
primaryColor = "#007bff"
backgroundColor = "#ffffff"
# Original secondaryBackgroundColor = "#f0f2f6"
secondaryBackgroundColor = "#e7f3ff"
textColor = "#262730"

[server]
maxUploadSize = 70
